server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB_NAME:auth}?useUnicode=yes&characterEncoding=UTF-8&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    database-name: auth
    username: ${MYSQL_USER_NAME:root}
    password: ${MYSQL_PASSWORD:1234}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

token:
  secret:
    key: ${TOKEN_SECRET_KEY:SpringBootPrototypeMSAApwefjijwoiefjiojweoifjwioefjoiwefjoiwefjiowefp12345678!!!!}
  access-token:
    plus-hour: ${ACCESS_TOKEN_PLUS_HOUR:1}
  refresh-token:
    plus-hour: ${REFRESH_TOKEN_PLUS_HOUR:12}

logging:
  level:
    root: ${LOGGING_LEVEL:INFO}

url:
  product: http://localhost:8083
