server:
  port: ${SERVER_PORT:8083}
spring:
  data:
    redis:
      host: localhost
      port: 6380
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB_NAME:product}?useUnicode=yes&characterEncoding=UTF-8&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    database-name: product
    username: ${MYSQL_USER_NAME:root}
    password: ${MYSQL_PASSWORD:1234}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers:
      - localhost:19092
      - localhost:19093
      - localhost:19094
    consumer:
      group-id: product-consume-group
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
aws:
  accessKey: ${R2_ACCESS_KEY}
  secretKey: ${R2_SECRET_KEY}
  s3:
    endpointUrl: ${R2_ENDPOINT_URL}
    region: ${R2_ENDPOINT_REGION}
    bucketName: ${R2_BUCKET_NAME}

logging:
  level:
    root: ${LOGGING_LEVEL:INFO}
#    org.apache.kafka: DEBUG
#    org.springframework.kafka: DEBUG

url:
  auth: http://localhost:8080
  r2: ${R2_URL}
