server:
  port: ${SERVER_PORT:8083}
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB_NAME:product}?useUnicode=yes&characterEncoding=UTF-8&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    database-name: product
    username: ${MYSQL_USER_NAME:root}
    password: ${MYSQL_PASSWORD:1234}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
aws:
  accessKey: ${R2_ACCESS_KEY}
  secretKey: ${R2_SECRET_KEY}
  s3:
    endpointUrl: ${R2_ENDPOINT_URL}
    region: ${R2_ENDPOINT_REGION}
    bucketName: ${R2_BUCKET_NAME}

logging:
  level:
    root: ${LOGGING_LEVEL:INFO}
